#!/usr/bin/env python3
from pathlib import Path
from urllib import parse


CURRENT_DIR = Path(__file__).parents[0]
INPUT_DIR = CURRENT_DIR / "icons"


TEMPLATE = """// This file is autogenerated by tools/process-identity-icons.py

export const IDENTITY_ICON_TEMPLATES = {{{}}};
"""


icons = "\n"
for file in INPUT_DIR.iterdir():
    print(file.name)
    identity = file.name.partition(".")[0]
    svg = file.open().read()
    encoded_svg = " ".join(svg.partition("-->")[2].split()).replace("> <", "><")
    icons += "  {}: '{}',\n".format(identity, encoded_svg)


(CURRENT_DIR / "identity-icon-templates.js").open("w").write(TEMPLATE.format(icons))
