name: autobuild

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Build
      run: |
        npm install
        npm run build

    - name: Publish
      uses: actions/upload-artifact@master
      with:
        name: build
        path: dist
